In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('taxi.csv')

In [4]:
data.head()

  Priceperweek\tPopulation\tMonthlyincome\tAverageparkingpermonth\tNumberofweeklyriders
0                      15\t1800000\t5800\t50\t192000
1                      15\t1790000\t6200\t50\t190400
2                      15\t1780000\t6400\t60\t191200
3                      25\t1778000\t6500\t60\t177600
4                      25\t1750000\t6550\t60\t176800

In [5]:
x = data.drop('Numberofweeklyriders', axis =1)
y = data['Numberofweeklyriders']

KeyError: "['Numberofweeklyriders'] not found in axis"

In [6]:
import pandas as pd

# Use sep='\t' to handle the tabs in your file
data = pd.read_csv('taxi.csv', sep='\t')

# Verify the columns are separated correctly now
print(data.columns)
data.head()

Index(['Priceperweek', 'Population', 'Monthlyincome', 'Averageparkingpermonth',
       'Numberofweeklyriders'],
      dtype='str')

,Priceperweek,Population,Monthlyincome,Averageparkingpermonth,Numberofweeklyriders
0,15,1800000,5800,50,192000
1,15,1790000,6200,50,190400
2,15,1780000,6400,60,191200
3,25,1778000,6500,60,177600
4,25,1750000,6550,60,176800

In [7]:
x = data.drop('Numberofweeklyriders', axis=1)
y = data['Numberofweeklyriders']

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [10]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [11]:
model.fit(x_train,y_train)

LinearRegression()

In [12]:
print("training score",model.score(x_train,y_train))

training score 0.9285840543940118

In [13]:
import pickle
pickle.dump(model,open('model.pkl','wb'))

In [14]:
model1 = pickle.load(open('model.pkl','rb'))

In [18]:
# Notice the double square brackets [[...]]
print(model1.predict([[63, 1610000, 16200, 200]]))

[154286.34654247]

c:\Users\thari\uber_project\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(